spring.application.name=aiforge-backend

spring.datasource.url=jdbc:mysql://localhost:3306/aiforge
spring.datasource.username=root
spring.datasource.password=Root@1234

spring.jpa.hibernate.ddl-auto=update

