spring.application.name=aiforge-backend


server.port=8080


tavily.api.key=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


openrouter.api.key=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